import assert from 'node:assert/strict';
import {AudioPreview} from '../dist/audio-preview.js';
import {PlaybackSession} from '../dist/playback-session.js';
const voices=[];globalThis.document={createElement(){let resolve;const voice={dataset:{},paused:true,preload:'',pause(){this.paused=true},play(){this.calls=(this.calls||0)+1;return new Promise(r=>resolve=()=>{this.paused=false;r()})},complete(){resolve()},removeAttribute(){},load(){}};voices.push(voice);return voice}};
const audio=new AudioPreview(),voice=voices[0];voice.dataset.key='first';audio.startVoice(voice);audio.startVoice(voice);assert.equal(voice.calls,1,'one pending play per voice');audio.pause();voice.complete();await new Promise(r=>setTimeout(r,0));assert.equal(voice.paused,true,'late play completion cannot resume stopped voice');assert.equal(voice.muted,true,'late native playback stays muted');
const values=[];audio.context={currentTime:1};const param={cancelScheduledValues(){},setValueAtTime(v){values.push(v)}};audio.graphs.set(voice,{output:{gain:param},feedback:{gain:param},wet:{gain:param}});audio.stopVoice(voice);assert.deepEqual(values,[0,0,0],'pause mutes output and delay feedback');
const playback=new PlaybackSession(),old=playback.begin();playback.stop();const fresh=playback.begin();assert.equal(playback.current(old),false);assert.equal(playback.current(fresh),true);audio.context=null;audio.graphs=new WeakMap();const oldVoices=[...audio.voices];audio.dispose();assert(audio.voices.every(v=>!oldVoices.includes(v)),'dispose replaces media elements already bound to a closed AudioContext');
globalThis.AudioContext=function(){};let resumes=0;audio.context={state:'interrupted',resume(){resumes++;this.state='running';return Promise.resolve()}};await audio.unlock();assert.equal(resumes,1,'user play recovers interrupted Safari audio');await audio.unlock();assert.equal(resumes,1);const connected=new WeakSet(),node=()=>({connect(){return this},gain:{setTargetAtTime(){},cancelScheduledValues(){},setValueAtTime(){}},frequency:{},delayTime:{}});globalThis.AudioContext=class{constructor(){this.currentTime=0;this.state='running';this.destination={}}createMediaElementSource(v){if(connected.has(v))throw Error('element already connected');connected.add(v);return node()}createGain(){return node()}createDelay(){return node()}createBiquadFilter(){return node()}close(){this.state='closed';return Promise.resolve()}};audio.context=null;assert(audio.graph(audio.voices[0]));const firstGraphVoice=audio.voices[0];audio.dispose();assert.notEqual(audio.voices[0],firstGraphVoice);assert(audio.graph(audio.voices[0]),'audio graph can be rebuilt after export/idle release');audio.dispose();
// No node can emit or form a unity-feedback loop during graph construction.
const edges=[],nodes=[],makeParam=()=>({value:1,events:[],cancelScheduledValues(){this.events.push('cancel')},setValueAtTime(v){this.value=v;this.events.push(v)},setTargetAtTime(){}}),make=kind=>{const n={kind,gain:makeParam(),delayTime:makeParam(),frequency:{},connect(to){edges.push([this,to]);return to}};nodes.push(n);return n};
let suspendResolve;
globalThis.AudioContext=class{constructor(){this.currentTime=0;this.state='running';this.destination=make('destination')}createMediaElementSource(){return make('source')}createGain(){return make('gain')}createDelay(){return make('delay')}createBiquadFilter(){return make('filter')}suspend(){return new Promise(r=>{suspendResolve=()=>{this.state='suspended';r()}})}resume(){this.state='running';return Promise.resolve()}close(){this.state='closed';return Promise.resolve()}};
const guarded=new AudioPreview(),g=guarded.graph(guarded.voices[0]);assert.equal(g.feedback.gain.value,0);assert.equal(g.wet.gain.value,0);assert.equal(g.output.gain.value,0);assert.equal(guarded.master.gain.value,0);assert.equal(g.delay.delayTime.value,.28);assert(edges.some(([from,to])=>from===g.output&&to===g.gate));assert(edges.some(([from,to])=>from===g.gate&&to===guarded.master));assert.equal(g.gate.gain.value,0);assert(!edges.some(([from,to])=>from===g.output&&to===guarded.context.destination));
guarded.setOutputEnabled(true);guarded.pause();assert.equal(guarded.master.gain.value,0,'stop silences all graphs at master output');assert.deepEqual(g.feedback.gain.events.slice(-2),['cancel',0]);assert.deepEqual(g.wet.gain.events.slice(-2),['cancel',0]);const unlocking=guarded.unlock();suspendResolve();await unlocking;assert.equal(guarded.context.state,'running','next play waits for pending suspend before resuming');assert.equal(guarded.master.gain.value,0,'resume alone cannot reopen audio output');guarded.sync({},0,false,()=>null);assert.equal(guarded.master.gain.value,0,'paused sync cannot restore scheduled sound');suspendResolve();await guarded.suspending;guarded.dispose();
delete globalThis.document;delete globalThis.AudioContext;
console.log('Audio pending-play cancellation, one play request, muted delay tails and stale playback sessions PASS');
