import assert from 'node:assert/strict';
import {execFileSync} from 'node:child_process';
import {clip,project,sequence,timing,compileTimeline,splitClip,sanitize} from '../dist/model.js';
import {clipAlpha,opacityAt,scaleAt,effectAlpha,textPose,frozenClip} from '../dist/creative.js';
import {sourceTime,held} from '../dist/mobile-model.js';
import {lookPresets,gradeRGB,adaptiveCinematic} from '../dist/look.js';
const m={id:'movie',duration:10,kind:'video'},p=project();p.media=[m];p.clips=[{...clip(m),start:0,layer:0}];
const still=frozenClip(p,p.clips[0].id,3,2);assert.equal(still.freezeAt,3);assert.equal(still.layer,2);assert.equal(still.audio.mute,true);
let row=sequence(p).find(r=>r.clip===still);assert.equal(row.end,5);assert.equal(sourceTime(row,4.8),3);assert(held(row,3));assert.equal(splitClip(still,3.01),null);
still.freezeDuration=4;assert.equal(sequence(p).find(r=>r.clip===still).end,7);
assert.equal(sanitize(JSON.parse(JSON.stringify(p))).clips[1].freezeDuration,4);
still.fadeIn=1;still.fadeOut=1;row=sequence(p).find(r=>r.clip===still);assert.equal(clipAlpha(row,3),0);assert.equal(clipAlpha(row,3.5),.5);assert.equal(clipAlpha(row,6.5),.5);
still.fadeIn=still.fadeOut=0;still.opacityKeyframes=[{time:0,value:0},{time:2,value:1},{time:4,value:0}];assert.equal(opacityAt(still,0,4),0);assert.equal(opacityAt(still,1,4),.5);assert.equal(opacityAt(still,2,4),1);assert.equal(opacityAt(still,3,4),.5);assert.equal(clipAlpha(row,4),.5);still.scale=1;still.scaleKeyframes=[{time:0,value:1},{time:2,value:2.5},{time:4,value:1}];assert.equal(scaleAt(still,0,4),1);assert.equal(scaleAt(still,1,4),1.75);assert.equal(scaleAt(still,2,4),2.5);assert.equal(scaleAt(still,3,4),1.75);
const e={type:'flash',start:2,duration:1,strength:.8};assert.equal(effectAlpha(e,2),.8);assert.equal(effectAlpha(e,2.5),.4);assert.equal(effectAlpha(e,3),0);e.type='black-out';assert.equal(effectAlpha(e,2),0);
const heldIn={type:'black-in',start:0,duration:3,hold:2,strength:1};assert.equal(effectAlpha(heldIn,1.9),1);assert(Math.abs(effectAlpha(heldIn,2.5)-.5)<1e-9);const heldOut={type:'black-out',start:4,duration:2,hold:.5,strength:1};assert.equal(effectAlpha(heldOut,4),0);assert.equal(effectAlpha(heldOut,5.8),1);
const txt={start:0,end:3,fadeIn:.4,fadeOut:.6,motion:'rise',x:.5,y:.8,opacity:1};assert.equal(textPose(txt,0).alpha,0);assert(textPose(txt,0).y>.8);assert.equal(textPose(txt,1).y,.8);assert(Math.abs(textPose(txt,2.7).alpha-.5)<1e-8);
// All looks, strengths, skin/highlight/shadow samples share native RGB math.
const samples=[];for(const color of Object.values(lookPresets))for(const amount of [0,.5,1,1.5])for(const rgb of [[.7,.45,.3],[.95,.9,.85],[.1,.12,.2]])samples.push({rgb,color,amount});
const native=JSON.parse(execFileSync('python3',['-c',"import sys,json;sys.path.insert(0,'engine');from color_engine import grade;print(json.dumps([grade(s['rgb'],s['color'],s['amount']) for s in json.load(sys.stdin)]))"],{input:JSON.stringify(samples),encoding:'utf8'}));
samples.forEach((s,i)=>gradeRGB(s.rgb,s.color,s.amount).forEach((v,j)=>assert(Math.abs(v-native[i][j])<1e-10)));
const mono=gradeRGB([.8,.4,.2],lookPresets.MONO,1.5);assert(Math.abs(mono[0]-mono[2])<1e-9);
const under=adaptiveCinematic({luma:.7,contrast:.2,clipping:.1});assert(under.exposure<0);assert(under.highlights<0);assert(under.blacks<0);assert(under.contrast>0);
const advanced={...lookPresets.CLEAN,gamma:24,fade:18,brilliance:31,brightness:-12,blackPoint:18,warmth:14,curveMaster:[[0,0],[.18,.08],[.43,.62],[.71,.79],[1,1]],curveRed:[[0,0],[.32,.29],[.68,.72],[1,1]],curveGreen:[[0,0],[.27,.23],[.74,.76],[1,1]],curveBlue:[[0,0],[.21,.15],[.63,.68],[1,1]]};const advancedNative=JSON.parse(execFileSync('python3',['-c',"import sys,json;sys.path.insert(0,'engine');from color_engine import grade;v=json.load(sys.stdin);print(json.dumps(grade(v['rgb'],v['color'],1)))"],{input:JSON.stringify({rgb:[.16,.44,.78],color:advanced}),encoding:'utf8'}));gradeRGB([.16,.44,.78],advanced,1).forEach((v,i)=>assert(Math.abs(v-advancedNative[i])<1e-10));
assert.notDeepEqual(gradeRGB([.2,.5,.8],advanced,1),gradeRGB([.2,.5,.8],lookPresets.CLEAN,1));
const threeWay={...lookPresets.CLEAN,balanceShadowHue:240,balanceShadowSaturation:55,balanceShadowLightness:-12,balanceMidtoneHue:185,balanceMidtoneSaturation:18,balanceMidtoneLightness:4,balanceHighlightHue:35,balanceHighlightSaturation:42,balanceHighlightLightness:8};
const threeNative=JSON.parse(execFileSync('python3',['-c',"import sys,json;sys.path.insert(0,'engine');from color_engine import grade;v=json.load(sys.stdin);print(json.dumps([grade(x,v['color'],1) for x in v['rgb']]))"],{input:JSON.stringify({rgb:[[.08,.08,.08],[.5,.5,.5],[.92,.92,.92]],color:threeWay}),encoding:'utf8'}));
[[.08,.08,.08],[.5,.5,.5],[.92,.92,.92]].forEach((rgb,i)=>gradeRGB(rgb,threeWay,1).forEach((v,j)=>assert(Math.abs(v-threeNative[i][j])<1e-9)));
const coolShadow=gradeRGB([.08,.08,.08],threeWay),warmHighlight=gradeRGB([.92,.92,.92],threeWay);assert(coolShadow[2]>coolShadow[0]);assert(warmHighlight[0]>warmHighlight[2]);
console.log('Creative: freeze/source invariance, fade/text timing, iPhone controls, curves, 3-way balance and native/browser RGB matches PASS');
