import assert from 'node:assert/strict';
import {openRenderFile,writeRenderChunk,storageFailureMessage} from '../dist/mobile-storage-output.js';
import {clip,project,sequence} from '../dist/model.js';
import {outputSettings,sourceTime} from '../dist/mobile-model.js';
let estimates=0,removed=0;
const written=new Uint8Array(10),handle={write(bytes,{at}){const count=Math.min(2,bytes.length);written.set(bytes.subarray(0,count),at);return count}};
const fileHandle={async createSyncAccessHandle(){return handle}};
const root={async getFileHandle(){return fileHandle},async removeEntry(){removed++}};
const storage={async estimate(){estimates++;return {quota:100,usage:100}},async getDirectory(){return {async getDirectoryHandle(){return root}}}};
const opened=await openRenderFile(storage,'export.mp4');
assert.equal(estimates,0);assert.equal(opened.handle,handle);
const data=new Uint8Array([99,1,2,3,4,88]).subarray(1,5);let checks=0;
writeRenderChunk(handle,data,3,()=>checks++);assert.deepEqual([...written.slice(3,7)],[1,2,3,4]);assert.equal(checks,2);
assert.throws(()=>writeRenderChunk({write(){return 0}},data,0),/保存できません/);
const quota=new DOMException('quota','QuotaExceededError');
assert.throws(()=>writeRenderChunk({write(){throw quota}},data,0),error=>error===quota);
assert.match(storageFailureMessage(quota),/Mac本体の空き容量とは別/);
assert.equal(storageFailureMessage(Error('decoder failed')),'decoder failed');
fileHandle.createSyncAccessHandle=async()=>{throw quota};await assert.rejects(openRenderFile(storage,'failed.mp4'),error=>error===quota);assert.equal(removed,1);
const p=project(),media={id:'mov',kind:'video',duration:104.406,width:3094,height:1912,fps:60};p.media=[media];p.clips=[{...clip(media),start:0,layer:2,speed:5.118,endSpeed:5.118}];
const cfg=outputSettings(p),row=sequence(p)[0];assert(Math.abs(cfg.duration-media.duration/5.118)<1e-6);
assert(Math.abs(sourceTime(row,1)-5.118)<1e-6);assert(cfg.frames===Math.ceil(cfg.duration*cfg.fps));
console.log('Export storage: advisory estimate does not block writes, partial writes, real quota errors, failure cleanup and 5.118x timeline PASS');
