import assert from 'node:assert/strict';
import {phoneLayout} from '../dist/iphone-ui.js';
import {bindTimeline} from '../dist/timeline-gestures.js';
import {project,clip,sequence} from '../dist/model.js';
assert.equal(phoneLayout({width:393,height:852,coarse:true,iphone:true}),true);
assert.equal(phoneLayout({width:852,height:393,coarse:true,iphone:true}),true);
assert.equal(phoneLayout({width:1440,height:900,coarse:false,iphone:false}),false);
assert.equal(phoneLayout({width:1024,height:768,coarse:true,iphone:false}),false);
assert.equal(phoneLayout({width:500,height:850,coarse:false,iphone:false}),true);
const m={id:'media',duration:10},p=project();p.media=[m];p.clips=[{...clip(m),start:0}];
let changes=0;const element={dataset:{clip:p.clips[0].id},style:{},classList:{add(){},remove(){}},setPointerCapture(){},clientWidth:1000,getBoundingClientRect:()=>({left:0,width:1000})};
const root={getBoundingClientRect:()=>({width:1000}),querySelectorAll:()=>[element]};
let moving=false;globalThis.document={body:{dataset:{ui:'phone'},classList:{contains:()=>moving}}};
const bind=()=>bindTimeline({root,rows:sequence(p),duration:10,select(){},begin(){changes++},finish(){},cancel(){},preview(){},media:()=>m,snap:()=>false,getLayer:()=>0});
const event=x=>({button:0,pointerType:'touch',pointerId:1,clientX:x,clientY:0,target:{closest:()=>null}});
bind();element.onpointerdown(event(0));element.onpointermove(event(100));element.onpointercancel();assert.equal(changes,0);assert.equal(p.clips[0].start,0);
moving=true;bind();element.onpointerdown(event(0));element.onpointermove(event(100));element.onpointerup(event(100));assert.equal(changes,1);assert.equal(p.clips[0].start,1);
delete globalThis.document;
console.log('Phone portrait/landscape routing, desktop/tablet preservation and scroll vs move PASS');
