import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import {execFileSync} from 'node:child_process';
import {streamingFrames} from '../dist/streaming-frames.js';import {AudioWindowReader} from '../dist/streaming-audio.js';import {Input,ALL_FORMATS,BlobSource} from '../dist/vendor/mediabunny.mjs';
globalThis.onmessage=null;const {audioRange}=await import('../dist/mobile-render-worker.js');
let iterators=0,closed=0,released=0;const sink={samplesAtTimestamps(stamps){iterators++;return(async function*(){try{for(const t of stamps)yield{timestamp:t,close(){closed++}}}finally{released++}})()}};
const frames=streamingFrames(sink,[0,.033,.066],s=>s.timestamp);assert.equal(await frames.next(),0);assert.equal(await frames.next(),.033);assert.equal(await frames.next(),.066);assert.equal(iterators,1);assert.equal(closed,3);await frames.close();await frames.close();assert.equal(released,1);
const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'pve-stream-pcm-'));let input,reader;
try{const file=path.join(tmp,'a.wav');execFileSync('ffmpeg',['-v','error','-f','lavfi','-i','sine=frequency=440:sample_rate=48000:duration=4','-c:a','pcm_s16le',file]);input=new Input({formats:ALL_FORMATS,source:new BlobSource(await fs.openAsBlob(file))});const track=await input.getPrimaryAudioTrack();reader=new AudioWindowReader(track);
for(const [start,end]of [[.123,.373],[.373,.623],[.623,.873],[1.4,1.65],[.05,.3]]){const actual=await reader.read(start,end),expected=await audioRange(track,start,end);assert.equal(actual.planes[0].length,expected.planes[0].length);for(let i=0;i<expected.planes[0].length;i++)assert(Math.abs(actual.planes[0][i]-expected.planes[0][i])<1e-6);assert(reader.chunks.length<80,'bounded PCM window');}
console.log('Sequential owned video samples and PCM window equivalence across fractional chunks, skips and loop rewind PASS');}finally{await reader?.close();input?.dispose();fs.rmSync(tmp,{recursive:true,force:true})}
