import assert from 'node:assert/strict';
import {sanitizeTexts,MAX_TEXT_LAYERS} from '../dist/model.js';
import {textStyle,textRasterPlacement} from '../dist/text-render.js';
import {captionPresets,captionDefaults,applyCaptionPreset,applyCaptionPresetStable} from '../dist/caption-presets.js';
import {textPose} from '../dist/creative.js';

const [text]=sanitizeTexts([{id:'title',text:'東京\nNIGHT',font:'Serif',align:'right',weight:'800',color:'#f2c8b0',box:'dark',outline:12,size:500,x:2,y:-1,opacity:2,fadeIn:8,fadeOut:-2,motion:'rise',motionDuration:4,start:1,end:0}]);
assert.equal(text.text,'東京\nNIGHT');
assert.equal(text.weight,800);
assert.equal(text.outline,12);
assert.equal(text.size,300);
assert.equal(text.x,1);
assert.equal(text.y,0);
assert.ok(text.end>text.start);
assert.equal(textStyle(text).outline,12);
assert.equal(textStyle(text).outlineColor,'#000000');
assert.equal(textStyle(text).box,'dark');
const [spaced]=sanitizeTexts([{text:'TYPE',letterSpacing:999,lineHeight:.1}]);
assert.equal(spaced.letterSpacing,50);assert.equal(spaced.lineHeight,.6);
assert.equal(sanitizeTexts(Array.from({length:MAX_TEXT_LAYERS+5},(_,i)=>({text:String(i)}))).length,MAX_TEXT_LAYERS);
assert.equal('raster' in sanitizeTexts([{text:'safe',raster:{data:'large'}}])[0],false);
const subtitle=captionDefaults(1,4,'subtitle');assert.equal(subtitle.outline,0);assert.equal(subtitle.y,.86);assert.equal(subtitle.shadow,false);
const custom={};applyCaptionPreset(custom,'lowerThird');assert.equal(custom.align,'left');assert.equal(custom.motion,'none');
const stable={font:'Serif',italic:true,size:71,x:.31,y:.68,align:'right',letterSpacing:2,lineHeight:1.4,motion:'pop'};applyCaptionPresetStable(stable,'tvImpact');assert.deepEqual({font:stable.font,italic:stable.italic,size:stable.size,x:stable.x,y:stable.y,align:stable.align,letterSpacing:stable.letterSpacing,lineHeight:stable.lineHeight,motion:stable.motion},{font:'Serif',italic:true,size:71,x:.31,y:.68,align:'right',letterSpacing:2,lineHeight:1.4,motion:'none'});
assert.equal(captionDefaults(0,2,'varietyYellow').outline,7);assert.equal(captionDefaults(0,2,'popPink').color,'#ff6fae');assert.equal(captionDefaults(0,2,'cornerTag').align,'left');
assert.equal(Object.keys(captionPresets).length,13);assert.equal(new Set(Object.values(captionPresets).map(p=>p.label)).size,13);assert.ok(Object.values(captionPresets).every(p=>p.sample&&p.description));assert.equal(captionPresets.headline.label,'ディープシャドウ');assert.equal(captionPresets.cornerTag.label,'ライム背景タグ');
const tv=captionDefaults(0,2,'tvBlueRed');assert.equal(tv.outerOutline,8);assert.deepEqual(tv.lineColors,['#ffffff','#b71318']);
const impact=captionDefaults(0,2,'tvImpact');impact.accentWords='欠かせない、モノ';const impactStyle=textStyle(impact);assert.equal(impactStyle.outerOutlineColor,'#ffffff');assert.deepEqual(impactStyle.accentWords,['欠かせない','モノ']);
const [decorated]=sanitizeTexts([{text:'装飾',outline:99,outlineColor:'#123456',shadow:true,shadowOpacity:2,shadowBlur:99,shadowX:-99,shadowY:99,box:'custom',boxColor:'#abcdef',boxOpacity:.4,boxPadding:.5,boxRadius:.2,motion:'pop'}]);
assert.equal(decorated.outline,20);assert.equal(decorated.shadowOpacity,1);assert.equal(decorated.shadowBlur,40);assert.equal(decorated.shadowX,-50);assert.equal(decorated.shadowY,50);assert.equal(decorated.box,'custom');assert.equal(decorated.motion,'pop');
assert.equal(sanitizeTexts([{text:'Italic',italic:true}])[0].italic,true);assert.equal(textStyle({text:'Italic',italic:true}).italic,true);
const raster={width:800,height:220,anchorX:400,anchorY:110,referenceWidth:1920,referenceHeight:1080},placed1080=textRasterPlacement({...subtitle,start:0,end:2},raster,1920,1080),placed4k=textRasterPlacement({...subtitle,start:0,end:2},raster,3840,2160);assert.equal(placed4k.scale,placed1080.scale*2);assert.equal(placed4k.x,placed1080.x*2);assert.equal(placed4k.y,placed1080.y*2);
const [rich]=sanitizeTexts([{text:'二重フチ',lineColors:['#112233','bad'],accentWords:'重要語',accentColor:'#ff817b',outerOutline:99,outerOutlineColor:'#abcdef'}]);assert.deepEqual(rich.lineColors,['#112233','#ffffff']);assert.equal(rich.accentWords,'重要語');assert.equal(rich.outerOutline,20);assert.equal(rich.outerOutlineColor,'#abcdef');
const [scaleText]=sanitizeTexts([{text:'ZOOM',start:2,end:8,motion:'scale',motionStart:1,motionEnd:4,motionScaleFrom:.5,motionScaleTo:2}]);assert.equal(textPose(scaleText,2.5).scale,.5);assert.ok(Math.abs(textPose(scaleText,4.5).scale-1.25)<1e-8);assert.equal(textPose(scaleText,7).scale,2);
const popText={text:'POP',start:0,end:3,motion:'pop',motionDuration:.3};assert.ok(textPose(popText,.05).scale<1);assert.equal(textPose(popText,2.9).scale,1);
console.log('Text layers: 300 captions, decoration, presets, validation and persisted raster exclusion PASS');
